#!/usr/bin/python3
import sys

def factorize(n):
    for i in range(2, int(n/2) + 1):
        if n % i == 0:
            return (i, n//i)
    return (n, 1)

try:
    with open(sys.argv[1], 'r') as f:
        for line in f:
            n = int(line.split('\n')[0])
            q, p = factorize(n)
            print("{:d}={:d}*{:d}".format(n , p, q))
except:
    print("Usage: factors <file>")
    sys.exit()
