#!/usr/bin/python3
import sys
import os 
import time

start_time = time.time()

def factorize(number):
      
     number = int(number)
     num1 = num2 = 0
     for i in range(2,number):
         if number % i == 0:
             num1 = i
             num2 = int(number / i)
             break

     print("{}={}*{}".format(number,num2,num1))


if len(sys.argv) != 2:

    print("Usage: factors <files>")

if not os.path.isfile(sys.argv[1]):

    print("file does not exist")

else:
    
    with open(sys.argv[1], 'r') as f:
        
        for line in f:
             factorize(line)   

