#!/usr/bin/python3
import sys

def is_prime(num):
    for y in range(2, int(num ** 0.5) + 1):
       if  n % y == 0:
           return False
    return True




def factorize(n):
    for i in range(2, int(n ** 0.5) + 1):
        if is_prime(i) and is_prime(n//i) and (n % i) == 0:
            a = i
            b = n//i
         
    return (a, b)

try:
    with open(sys.argv[1], 'r') as f:
        for line in f:
            n = int(line)
            q, p = factorize(n)
            print("{}={}*{}".format(n , p, q))
except:
    print("Usage: factors <file>")
    sys.exit()
